// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ftjvmwoudgcswntgxrww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0anZtd291ZGdjc3dudGd4cnd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM4OTcyMTQsImV4cCI6MjA3OTQ3MzIxNH0.n6KZHnSPevBi3yhv_ad2ke90K2kFCfMlFNEvXJBuo0o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);